//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: InariPokerData.proto
namespace InariPoker
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitData")]
  public partial class PlayerInitData : global::ProtoBuf.IExtensible
  {
    public PlayerInitData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OtherPlayerInitData")]
  public partial class OtherPlayerInitData : global::ProtoBuf.IExtensible
  {
    public OtherPlayerInitData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private int _cardsum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cardsum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardsum
    {
      get { return _cardsum; }
      set { _cardsum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInitDatas")]
  public partial class PlayerInitDatas : global::ProtoBuf.IExtensible
  {
    public PlayerInitDatas() {}
    
    private InariPoker.PlayerInitData _player;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public InariPoker.PlayerInitData player
    {
      get { return _player; }
      set { _player = value; }
    }
    private readonly global::System.Collections.Generic.List<InariPoker.OtherPlayerInitData> _others = new global::System.Collections.Generic.List<InariPoker.OtherPlayerInitData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"others", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<InariPoker.OtherPlayerInitData> others
    {
      get { return _others; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TurnData")]
  public partial class TurnData : global::ProtoBuf.IExtensible
  {
    public TurnData() {}
    
    private int _turnuserid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"turnuserid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int turnuserid
    {
      get { return _turnuserid; }
      set { _turnuserid = value; }
    }
    private readonly global::System.Collections.Generic.List<InariPoker.TurnDirection> _directions = new global::System.Collections.Generic.List<InariPoker.TurnDirection>();
    [global::ProtoBuf.ProtoMember(2, Name=@"directions", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<InariPoker.TurnDirection> directions
    {
      get { return _directions; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TurnDirection")]
  public partial class TurnDirection : global::ProtoBuf.IExtensible
  {
    public TurnDirection() {}
    
    private int _srcuserid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"srcuserid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int srcuserid
    {
      get { return _srcuserid; }
      set { _srcuserid = value; }
    }
    private int _destuserid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"destuserid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int destuserid
    {
      get { return _destuserid; }
      set { _destuserid = value; }
    }
    private int _cardtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"cardtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardtype
    {
      get { return _cardtype; }
      set { _cardtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TrueOrLieData")]
  public partial class TrueOrLieData : global::ProtoBuf.IExtensible
  {
    public TrueOrLieData() {}
    
    private bool _declare;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"declare", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool declare
    {
      get { return _declare; }
      set { _declare = value; }
    }
    private int _cardtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cardtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardtype
    {
      get { return _cardtype; }
      set { _cardtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeclareCardData")]
  public partial class DeclareCardData : global::ProtoBuf.IExtensible
  {
    public DeclareCardData() {}
    
    private int _cardtype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cardtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cardtype
    {
      get { return _cardtype; }
      set { _cardtype = value; }
    }
    private int _userid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private int _deccardtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"deccardtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deccardtype
    {
      get { return _deccardtype; }
      set { _deccardtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoarData")]
  public partial class RoarData : global::ProtoBuf.IExtensible
  {
    public RoarData() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private int _roartype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roartype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roartype
    {
      get { return _roartype; }
      set { _roartype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}