//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LobbyState.proto
namespace InariPoker
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LobbyState")]
  public partial class LobbyState : global::ProtoBuf.IExtensible
  {
    public LobbyState() {}
    
    private readonly global::System.Collections.Generic.List<InariPoker.RoomSummary> _summaries = new global::System.Collections.Generic.List<InariPoker.RoomSummary>();
    [global::ProtoBuf.ProtoMember(1, Name=@"summaries", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<InariPoker.RoomSummary> summaries
    {
      get { return _summaries; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomSummary")]
  public partial class RoomSummary : global::ProtoBuf.IExtensible
  {
    public RoomSummary() {}
    
    private int _roomid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private int _roomstate;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"roomstate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomstate
    {
      get { return _roomstate; }
      set { _roomstate = value; }
    }
    private int _playernum;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playernum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playernum
    {
      get { return _playernum; }
      set { _playernum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomState")]
  public partial class RoomState : global::ProtoBuf.IExtensible
  {
    public RoomState() {}
    
    private int _roomid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"roomid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int roomid
    {
      get { return _roomid; }
      set { _roomid = value; }
    }
    private readonly global::System.Collections.Generic.List<InariPoker.PlayerState> _players = new global::System.Collections.Generic.List<InariPoker.PlayerState>();
    [global::ProtoBuf.ProtoMember(2, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<InariPoker.PlayerState> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerState")]
  public partial class PlayerState : global::ProtoBuf.IExtensible
  {
    public PlayerState() {}
    
    private int _userid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int userid
    {
      get { return _userid; }
      set { _userid = value; }
    }
    private string _username;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private bool _ready;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool ready
    {
      get { return _ready; }
      set { _ready = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}